from .shufflenetv2 import shufflenet_v2_x1_0
from .shufflenetv2_segmantationplus import shufflenet_v2_x1_0 as segmentation_shufflenetplus_v2_x1_0
from .shufflenetv2_multi_taskplus import shufflenet_v2_x1_0 as multi_task_shufflenetplus_v2_x1_0
